#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Fri Dec 28 16:13:28 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((200, 250))
        self.username_form = wx.TextCtrl(self, wx.ID_ANY, "")
        self.password_form = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.login_button = wx.Button(self, wx.ID_ANY, "Login")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.apply, self.login_button)
        self.Bind(wx.EVT_CLOSE, self.on_success, self.dialog)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("gibc")
        self.SetSize((200, 250))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        username_label = wx.StaticText(self, wx.ID_ANY, "Username", style=wx.ALIGN_CENTER)
        username_label.SetFont(wx.Font(10, wx.SWISS, wx.NORMAL, wx.BOLD, 0, "Sans"))
        sizer_2.Add(username_label, 0, wx.ALIGN_CENTER | wx.EXPAND | wx.TOP, 10)
        sizer_2.Add(self.username_form, 0, wx.ALL | wx.EXPAND, 10)
        password_label = wx.StaticText(self, wx.ID_ANY, "Password", style=wx.ALIGN_CENTER)
        password_label.SetFont(wx.Font(10, wx.SWISS, wx.NORMAL, wx.BOLD, 0, "Sans"))
        sizer_2.Add(password_label, 0, wx.EXPAND, 0)
        sizer_2.Add(self.password_form, 0, wx.ALL | wx.EXPAND, 10)
        sizer_2.Add(self.login_button, 0, wx.ALIGN_CENTER, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

    def apply(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'apply' not implemented!")
        event.Skip()

    def on_success(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'on_success' not implemented!")
        event.Skip()

# end of class MyDialog

class LoginWindow(wx.App):
    def OnInit(self):
        self.dialog = MyDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True

# end of class LoginWindow

if __name__ == "__main__":
    LoginWindow = LoginWindow(0)
    LoginWindow.MainLoop()
